POST http://localhost:2525/imposters
content-Type: application/json

{
    "name": "Ex3",
    "port": 4553,
    "protocol": "http",
    "stubs": [{
        "responses": [{
            "is": {
                "statusCode": 200,
                "body": {
                    "marcas": []
                }
            }
        }],
        "predicates":[{
            "and": [
                {
                "equals": {
                    "path": "/api/carros",
                    "method": "GET",
                    "headers": { "Content-Type": "application/json" }
                }
                },
                {
                "not": {
                    "contains": { "body": "requiredField" },
                    "caseSensitive": true
                }
                }
            ]
        }]
    }]
}

###
GET http://localhost:4553/api/carros
Content-Type: application/json