POST http://localhost:2525/imposters
content-Type: application/json

{
    "name": "Ex4",
    "port": 4554,
    "protocol": "http",
    "stubs": [{
        "responses": [{
            "is": {
                "statusCode": 200,
                "headers": { "Content-Type": "application/json" },
                "body": {
                    "status": "Ok",
                    "token": "validtoken"
                }
            }
        }],
        "predicates":[{
            "and": [
                {
                "deepEquals": {
                    "path": "/api/login",
                    "method": "POST",
                    "headers": { "Content-Type": "application/json" },
                    "body": { 
                        "username": "admin",
                        "password": "secret"
                    }
                }
                }
            ]
        }]
    }]
}

###
GET http://localhost:4554/api/login
Content-Type: application/json

{ 
  "username": "admin", 
  "password": "secret" 
}