POST http://localhost:2525/imposters
content-Type: application/json

{
    "name": "Ex4",
    "port": 4554,
    "protocol": "http",
    "stubs": [{
        "responses": [{
            "is": {
                "statusCode": 200,
                "body": {
                    "credential": ["username": "Admin",
                                   "password": "secret"]
                }
            }
        }],
        "predicates":[{
            "and": [
                {
                "equals": {
                    "path": "/api/login",
                    "method": "POST",
                    "headers": { "Content-Type": "application/json" },
                    "query": { }
                }
                },
                {
                "not": {
                    "contains": { "body": "requiredField" },
                    "caseSensitive": true
                }
                }
            ]
        }]
    }]
}

###
GET http://localhost:4553/api/carros
Content-Type: application/json