POST http://localhost:2525/imposters
content-Type: application/json

{
   "name":"Ex9",
   "port":4559,
   "protocol":"http",
   "stubs":[
      {
         "responses":[
            {
               "is":{
                  "statusCode": 201,
                  "headers":{
                     "Content-Type":"application/json",
                     "Location":"/api/temperature"
                  },
                  "body":{
                     "status":"Created"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/temperature",
                  "method":"POST"
               },
               "caseSensitive":true
            },
            {
               "contains":{
                  "body":{
                     "value":"34",
                     "sensor_id": "1"

                  }
               }
            }
         ]
      }
   ]
}

###
POST http://localhost:4559/api/temperature
Content-Type: application/json

{
    "value": "34",
    "sensor_id": "1"
}

###
DELETE http://localhost:2525/imposters/4559
Content-Type: application/json