POST http://localhost:2525/imposters
Content-Type: application/json

{
   "name": "Ex1",
   "port": 4571,
   "protocol": "http",
   "stubs": [
      {
         "responses": [
            {
               "is": {
                  "statusCode": 200,
                  "headers": {
                     "Content-Type": "application/json"
                  },
                  "body": {
                     "nome": "Andre",
                     "idade": "18",
                     "curso": "mecanica"
                  }
               }
            }
         ],
         "predicates": [
            {
               "equals": {
                  "path": "/api/student/1",
                  "method": "GET"
               }
            }
         ]
      },
      {
         "responses": [
            {
               "is": {
                  "statusCode": 200,
                  "headers": {
                     "Content-Type": "application/json"
                  },
                  "body": {
                     "nome": "Gonçalo",
                     "idade": "16",
                     "curso": "mecanica"
                  }
               }
            }
         ],
          "predicates": [
            {
               "equals": {
                  "path": "/api/student/2",
                  "method": "GET"
               }
            }
         ]
      },
      {
         "responses": [
            {
               "is": {
                  "statusCode": 200,
                  "headers": {
                     "Content-Type": "application/json"
                  },
                  "body": {
                     "nome": "Daniel",
                     "idade": "17",
                     "curso": "cozinha"
                  }
               }
            }
         ],
        "predicates": [
            {
               "equals": {
                  "path": "/api/student/3",
                  "method": "GET"
               }
            }
         ]
      },
      {
         "responses": [
            {
               "is": {
                  "statusCode": 200,
                  "headers": {
                     "Content-Type": "application/json"
                  },
                  "body": {
                     "nome": "Henrique",
                     "idade": "17",
                     "curso": "programação"
                  }
               }
            }
         ],
        "predicates": [
            {
               "equals": {
                  "path": "/api/student/4",
                  "method": "GET"
               }
            }
         ]
      }
   ]
}

### ------- 1 ---------
GET http://localhost:4571/api/student/1
Content-Type: application/json

### ------- 2 ---------
GET http://localhost:4571/api/student/2
Content-Type: application/json

### ------- 3 ---------
GET http://localhost:4571/api/student/3
Content-Type: application/json

### ------- 4 ---------
GET http://localhost:4571/api/student/4
Content-Type: application/json

### ------- ALL ---------
GET http://localhost:4571/api/student
Content-Type: application/json

### 
DELETE http://localhost:2525/imposters/4571
Content-Type: application/json