POST http://localhost:2525/imposters
content-Type: application/json

{
   "name":"Ex7",
   "port":4557,
   "protocol":"http",
   "stubs":[
      {
         "responses":[
            {
               "is":{
                  "statusCode":201,
                  "headers":{
                     "Content-Type":"application/json",
                     "Location":"/api/users/1"
                  },
                  "body":{
                     "status":"Created Succesfully",
                     "token":"Welcome!"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/users/1",
                  "method":"POST"
               },
               "caseSensitive":true
            },
            {
               "not":{
                  "contains":{
                     "body":{
                        "email":"exists@gmail.not"
                     }
                  }
               }
            }
         ]
      }
   ]
}

###
POST http://localhost:4557/api/users/1
Content-Type: application/json

{
   "email": "exi@gmail.not",
   "username": "admin",
   "idade": "22"

}

###
DELETE http://localhost:2525/imposters/4557
Content-Type: application/json