POST http://localhost:2525/imposters
content-Type: application/json

{
   "name":"Ex8",
   "port":4558,
   "protocol":"http",
   "stubs":[
      {
         "responses":[
            {
               "is":{
                  "statusCode": 400,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "status":"Missing Field Required!"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/temperature",
                  "method":"POST"
               },
               "caseSensitive":true
            },
            {
               "not":{
                  "contains":{
                     "body":{
                        "value": 23
                     }
                  }
               }
            }
         ]
      }
   ]
}

###
POST http://localhost:4558/api/temperature
Content-Type: application/json

{
    "value": "Coisa"
}

###
DELETE http://localhost:2525/imposters/4558
Content-Type: application/json